const motivationalSentences = [
    "Every bug you fix is a step closer to becoming a debugging ninja.",
    "The algorithms you master today will solve the problems of tomorrow.",
    "Persistence in coding opens doors to endless possibilities.",
    "Innovation flourishes when you embrace the unknown.",
    "Celebrate each 'Aha!' moment; they mark your progress.",
    "Code with passion, and your programs will reflect your dedication.",
    "Connect with the global coding community; collaboration fuels innovation.",
    "Your journey in computer science is a marathon, not a sprint.",
    "Mistakes are learning opportunities in disguise.",
    "Efficiency in code comes from thoughtful design.",
    "Believe in your ability to tackle complex algorithms.",
    "Learning to code is empowering; it gives you the ability to create.",
    "Seek challenges; they are the gateway to growth.",
    "Stay curious; there's always something new to discover in programming.",
    "Embrace the beauty of elegant code; simplicity is powerful.",
    "Your dedication to problem-solving sets you apart.",
    "Perseverance in debugging pays off; each fix makes your code stronger.",
    "Collaborate with peers; together, you can achieve more.",
    "Strive for mastery in data structures; they are the backbone of efficient algorithms.",
    "Approach algorithms with creativity and logical thinking.",
    "Failure is a temporary setback; resilience leads to success.",
    "Stay updated with industry trends; knowledge is your competitive edge.",
    "Learn from both success and failure; both are valuable teachers.",
    "Coding languages are your tools; master them to craft solutions.",
    "Visualize your code; clarity leads to better solutions.",
    "Take breaks; sometimes stepping away helps you see the solution.",
    "Stay organized in your coding; good habits lead to efficiency.",
    "Understand the problem thoroughly before diving into solutions.",
    "Your commitment to learning today shapes the innovations of tomorrow.",
    "Patience is key in coding; complex problems take time to solve.",
    "Celebrate your uniqueness; diversity strengthens the tech community.",
    "Share your knowledge; teaching others deepens your own understanding.",
    "Your coding journey is a story of growth and discovery.",
    "Be adaptable; technology evolves, and so should your skills.",
    "Stay humble; there's always more to learn in computer science.",
    "Attention to detail separates good code from great code.",
    "Take ownership of your projects; pride in your work fuels motivation.",
    "Break down problems into manageable parts; it makes solutions clearer.",
    "Document your code; clarity helps future you and your collaborators.",
    "Seek mentors who inspire and challenge you to think beyond.",
    "Network with professionals in the field; connections open doors.",
    "Code with empathy; consider the user experience in your designs.",
    "Explore open-source projects; they offer real-world coding experience.",
    "Set goals; they give direction and purpose to your coding journey.",
    "Stay disciplined in your practice; consistency breeds expertise.",
    "Stay curious about emerging technologies; they shape the future.",
    "Your passion for coding drives innovation; let it fuel your projects.",
    "Strive for balance; a healthy mind fuels creativity.",
    "Take pride in your achievements, big and small.",
    "Visualize success; it motivates you through challenges.",
    "Seek feedback on your code; constructive criticism improves your skills.",
    "Stay patient with yourself; learning complex concepts takes time.",
    "Coding is problem-solving; relish the satisfaction of cracking a tough problem.",
    "Keep your code clean; it's a reflection of your professionalism.",
    "Learn to manage time effectively; it enhances productivity.",
    "Embrace uncertainty; it's where innovation thrives.",
    "Stay ethical in your coding practices; integrity builds trust.",
    "Stay proactive in your learning; seek out knowledge beyond the classroom.",
    "Stay resilient; setbacks are temporary, but learning is permanent.",
    "Stay focused on solutions; dwelling on problems hinders progress.",
    "Your passion for coding is contagious; share it with others.",
    "Learn from the masters; study the code of experienced developers.",
    "Stay updated with the latest tools; they streamline your workflow.",
    "Celebrate diversity in tech; different perspectives drive innovation.",
    "Embrace challenges; they strengthen your problem-solving skills.",
    "Your coding skills are a passport to a global career.",
    "Master algorithms; they're the foundation of efficient software.",
    "Coding is a journey of continuous learning; enjoy the ride.",
    "Stay persistent; every setback is a setup for a comeback.",
    "Coding is creative expression; let your code tell a story.",
    "Stay hungry for knowledge; it fuels your growth.",
    "Stay humble in success; there's always room to improve.",
    "Your curiosity is your compass in the world of coding.",
    "Practice makes progress; embrace the iterative nature of coding.",
    "Stay optimistic; a positive mindset fuels resilience.",
    "Learn from your mistakes; they pave the way for improvement.",
    "Code with integrity; your reputation is as important as your skills.",
    "Stay adaptable; technology evolves, so should your approach.",
    "Collaborate across disciplines; diverse teams drive innovation.",
    "Your coding journey is unique; embrace your own path.",
    "Strive for elegance in your solutions; simplicity is powerful.",
    "Stay proactive; anticipate challenges before they arise.",
    "Persevere through complexity; the reward is in mastering it.",
    "Stay organized; it enhances both productivity and creativity.",
    "Believe in your ability to solve any coding challenge.",
    "Coding is a craft; hone your skills with dedication.",
    "Seek mentors who challenge and support your growth.",
    "Stay curious about emerging technologies; they shape the future.",
    "Strive for clarity in your code; it enhances readability.",
    "Stay patient with yourself; learning complex concepts takes time.",
    "Stay disciplined in your practice; consistency breeds expertise.",
    "Stay resilient; setbacks are temporary, but learning is permanent.",
    "Stay focused on solutions; dwelling on problems hinders progress.",
    "Your passion for coding is contagious; share it with others.",
    "Stay proactive in your learning; seek out knowledge beyond the classroom.",
    "Learn from the masters; study the code of experienced developers.",
    "Stay updated with the latest tools; they streamline your workflow.",
    "Celebrate diversity in tech; different perspectives drive innovation.",
    "Embrace challenges; they strengthen your problem-solving skills.",
    "Your coding skills are a passport to a global career."
];

let sentence = document.getElementById('motivation-text');
let button = document.getElementById('motivationButton');
function selectRandom(){
    let index = Math.floor(Math.random() * 100);
    sentence.innerHTML = motivationalSentences[index];
    button.innerHTML = 'One more'; 
}

button.addEventListener('click', selectRandom);

